# Generated by Django 3.2.5 on 2021-07-28 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizes.quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
