# Generated by Django 3.2.5 on 2021-07-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=120)),
                ('time', models.IntegerField(help_text='durations of the quiz in minutes')),
                ('requred_score_to_pass', models.IntegerField(help_text='score in %')),
                ('difficulty', models.CharField(choices=[('easy,', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=10)),
            ],
        ),
    ]
