# Generated by Django 3.2.5 on 2021-07-28 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210728_0450'),
        ('student', '0002_auto_20210728_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='teacher.question'),
        ),
    ]
